Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - '3529/0/about_blocks.rb'
    - '3529/0/about_methods.rb'
    - '3529/0/about_strings.rb'
    - '3529/0/about_sandwich_code.rb'
    - '3529/0/about_open_classes.rb'
    - '3529/0/about_java_interop.rb'
    - '3529/0/about_control_statements.rb'
    - '3529/0/about_exceptions.rb'
    - '3529/0/about_modules.rb'
    - '3529/0/versioning_spec.rb'
    - '3529/0/neo.rb'
    - '3529/0/about_variable_scope.rb'
    - '3529/0/about_message_passing.rb'
    - '3529/0/about_classes.rb'
    - '3529/0/about_class_methods.rb'
    - '3529/0/about_triangle_project_2.rb'
    - '3529/0/about_scoring_project.rb'
    - '3529/0/about_proxy_object_project.rb'
    - '3529/0/about_iteration.rb'
    - '3529/0/about_regular_expressions.rb'
    - '3529/0/triangle.rb'



Metrics/LineLength:
  Max: 100